@Api_HostAddress = https://api-efrmql6nan6de.azurewebsites.net

POST {{Api_HostAddress}}/api/urls
Accept: application/json
Content-Type: application/json

{
  "LongUrl": "https://www.hackerrank.com/"
}

###
