name: CosmosDB Trigger Function

on:
  push:
    branches: ["main"]
    paths:
      - CosmosDbTrigger/**
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "CosmosDbTrigger/src/Shortify.CosmosDbtriggerFunction"
  DOTNET_VERSION: "8.0.x"

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Debug Directory Structure"
        shell: bash
        run: |
          echo "Current directory:"
          pwd
          echo "\nRoot directory contents:"
          ls -la
          echo "\nCosmosDbTrigger directory contents (if exists):"
          ls -la CosmosDbTrigger || echo "CosmosDbTrigger directory not found"

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Build Function App"
        shell: bash
        run: |
          if [ ! -d "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}" ]; then
            echo "Error: Directory ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} not found"
            echo "Available directories:"
            find . -type d -maxdepth 3
            exit 1
          fi

          cd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          dotnet build --configuration Release --output ./output

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
          publish-profile: ${{ secrets.AZURE_COSMOSTRIGGER_FUNCTIONAPP_PUBLISH_PROFILE }}
