@Shortify.TokenRangeService_HostAddress = https://token-range-service-efrmql6nan6de.azurewebsites.net

POST {{Shortify.TokenRangeService_HostAddress}}/assign/
Accept: application/json
Content-Type: application/json

{
  "Key": "A1234"
}
###
