@Shortify.TokenRangeService_HostAddress = https://token-range-service-efrmql6nan6de.azurewebsites.net

POST https://token-range-service-efrmql6nan6de.azurewebsites.net/assign
Accept: application/json
Content-Type: application/json

{
  "key": "A1234"
}
###
